### ISSUE TITLE
Item descriptions cant be saved[BUG]

### ISSUE THREAD

**Issue by Madd0Dreamer** [Larkinabout/fvtt-dnd5e-custom-counters#1]
Good news first, ive been dying for a module like this my hype is real! Now for bad news, when using the module once adding a custom counter and marking it as visible, item descriptions on character sheets can't be saved. The text editing options disappear. I have tested with it being the only active module and the bug persists.

**Versions:**
- Module: 0.1.1
- System:dnd5e 2.3.1
- Foundry VTT: 11.308
- Browser: Firefox, Edge

**Comment by Larkinabout** [comment]
Fixed in 0.1.2. Thanks!
